apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- storageclass.yaml
- configmap.yaml
- secrets.yaml
- postgres.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml
- networkpolicy.yaml
- clusterissuer.yaml
- argocd-ingress.yaml
